#!/bin/zsh

if [[ $# -ne 1 ]]; then
  kubectl config current-context
else
  case "$1" in
    "p" | "prod")
      kubectl config use-context prod
    ;;
    "d" | "dev")
      kubectl config use-context dev
    ;;
    "s" | "stage")
      kubectl config use-context staging
    ;;
    "l" | "labs")
      kubectl config use-context labs
    ;;
    "pi")
      kubectl config use-context pi
    ;;
    *)
      echo invalid context
    ;;
esac
fi

