#!/bin/bash
if [ $# -ne 1 ]; then
  echo "Usage: kdp [partial-pod-name]"
else
  pod=`kubectl get pods|grep $1|cut -f 1 -d " "`

  if [ -z "$pod" ]
  then
    echo "Cannot find pod to delete"
  else
    kubectl delete pod $pod
  fi
fi
